services:
  db:
    image: mysql:8.0.28
    environment: 
      MYSQL_ROOT_PASSWORD: jsal382!2
    cpu_count: '2'
    mem_limit: '1G'
    expose:
      - 3306
    volumes:  
      - services-db:/var/lib/db:cached
    networks:
      - backend

  nodeapp:
    build: ./nodeApp
    ports:
      - 80:8080
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  services-db:
